// ===== ../shared/theme/index.mjs =====
const __m1__Users_tarunagarwal_Documents_1_App_Developement_Tarun_Open_Access_UK_shared_theme_index_mjs = (() => {
// shared/theme/index.mjs
const THEME_STORAGE_KEY = 'open-access-uk:theme';

const VALID = new Set(['light', 'dark']);

function resolveInitialTheme({ stored, prefersDark } = {}) {
  if (VALID.has(stored)) return stored;
  return prefersDark ? 'dark' : 'light';
}

function nextTheme(current) {
  return current === 'dark' ? 'light' : 'dark';
}

return { THEME_STORAGE_KEY, resolveInitialTheme, nextTheme };
})();

// ===== src/theme.js =====
const __m2__Users_tarunagarwal_Documents_1_App_Developement_Tarun_Open_Access_UK_open_access_uk_site_src_theme_js = (() => {
const { THEME_STORAGE_KEY: THEME_STORAGE_KEY, resolveInitialTheme: resolveInitialTheme, nextTheme: nextTheme } = __m1__Users_tarunagarwal_Documents_1_App_Developement_Tarun_Open_Access_UK_shared_theme_index_mjs;
// <app>/src/theme.js

function readStored() {
  try {
    return window.localStorage.getItem(THEME_STORAGE_KEY);
  } catch {
    return null;
  }
}

function writeStored(value) {
  try {
    window.localStorage.setItem(THEME_STORAGE_KEY, value);
  } catch {
    /* private mode: theme still applies for this session */
  }
}

function apply(theme, toggle) {
  document.documentElement.setAttribute('data-theme', theme);
  if (toggle) {
    toggle.setAttribute('aria-pressed', String(theme === 'dark'));
    toggle.textContent = theme === 'dark' ? 'Light theme' : 'Dark theme';
  }
}

function initTheme(toggleSelector = '#theme-toggle') {
  const prefersDark = window.matchMedia?.('(prefers-color-scheme: dark)').matches ?? false;
  const toggle = document.querySelector(toggleSelector);
  let theme = resolveInitialTheme({ stored: readStored(), prefersDark });
  apply(theme, toggle);

  toggle?.addEventListener('click', () => {
    theme = nextTheme(theme);
    apply(theme, toggle);
    writeStored(theme);
  });
}

return { initTheme };
})();

// ===== src/analytics.js =====
const __m3__Users_tarunagarwal_Documents_1_App_Developement_Tarun_Open_Access_UK_open_access_uk_site_src_analytics_js = (() => {
function track(_eventName, _payload = {}) {
  // Analytics is intentionally off by default. Do not capture generated content
  // or personal data if optional analytics is reviewed and enabled later.
}

return { track };
})();

// ===== src/dom.js =====
const __m4__Users_tarunagarwal_Documents_1_App_Developement_Tarun_Open_Access_UK_open_access_uk_site_src_dom_js = (() => {
function textElement(tag, text) {
  const element = document.createElement(tag);
  element.textContent = text;
  return element;
}

function setPressed(buttons, activeKey) {
  buttons.forEach((button) => {
    const selected = button.dataset.workflow === activeKey;
    button.classList.toggle('is-selected', selected);
    button.setAttribute('aria-pressed', String(selected));
  });
}

function setStatus(node, message) {
  if (node) node.textContent = message;
}

return { textElement, setPressed, setStatus };
})();

// ===== src/repositories.js =====
const __m5__Users_tarunagarwal_Documents_1_App_Developement_Tarun_Open_Access_UK_open_access_uk_site_src_repositories_js = (() => {
// Generated by scripts/sync-static-metadata.mjs. Do not edit by hand.
const publicRepositories = [
  {
    "id": "letter-generator",
    "name": "Public-Service Letter Generator",
    "repo": "tarunag10/letter-generator",
    "demo": "https://letter-generator-psi.vercel.app/",
    "category": "letters",
    "status": "usable",
    "risk_level": "high",
    "maintainers": [
      "tarunag10"
    ],
    "githubUrl": "https://github.com/tarunag10/letter-generator",
    "toolKey": "letters",
    "iconClass": "blue",
    "icon": "▣",
    "summary": "Create useful letters, plan response windows, and follow up with confidence."
  },
  {
    "id": "accessible-forms",
    "name": "Accessible Public Forms",
    "repo": "tarunag10/accessible-forms",
    "demo": "https://accessible-forms-two.vercel.app/",
    "category": "forms",
    "status": "usable",
    "risk_level": "medium",
    "maintainers": [
      "tarunag10"
    ],
    "githubUrl": "https://github.com/tarunag10/accessible-forms",
    "toolKey": "forms",
    "iconClass": "green",
    "icon": "▤",
    "summary": "Check readiness, export JSON specs, and generate remediation reports."
  },
  {
    "id": "public-service-directory",
    "name": "Public Service Directory",
    "repo": "tarunag10/public-service-directory",
    "demo": "https://public-service-directory.vercel.app/",
    "category": "directory",
    "status": "usable",
    "risk_level": "high",
    "maintainers": [
      "tarunag10"
    ],
    "githubUrl": "https://github.com/tarunag10/public-service-directory",
    "toolKey": "directory",
    "iconClass": "lime",
    "icon": "⌂",
    "summary": "Find the right route and generate escalation readiness reports."
  },
  {
    "id": "legal-templates",
    "name": "Legal Templates UK",
    "repo": "tarunag10/legal-templates",
    "demo": "https://legal-templates-seven.vercel.app/",
    "category": "templates",
    "status": "usable",
    "risk_level": "high",
    "maintainers": [
      "tarunag10"
    ],
    "githubUrl": "https://github.com/tarunag10/legal-templates",
    "toolKey": "templates",
    "iconClass": "violet",
    "icon": "◫",
    "summary": "Bundle plain-English templates into reusable text and Markdown packs."
  },
  {
    "id": "design-system",
    "name": "Open Access Design System",
    "repo": "tarunag10/design-system",
    "demo": "https://design-system-two-delta.vercel.app/",
    "category": "design-system",
    "status": "usable",
    "risk_level": "low",
    "maintainers": [
      "tarunag10"
    ],
    "githubUrl": "https://github.com/tarunag10/design-system",
    "toolKey": "design",
    "iconClass": "cyan",
    "icon": "⌘",
    "summary": "Use accessible components, tokens, and implementation recipes."
  },
  {
    "id": "foi-tracker",
    "name": "FOI Response Tracker",
    "repo": "tarunag10/foi-tracker",
    "demo": "https://foi-tracker.vercel.app/",
    "category": "foi",
    "status": "usable",
    "risk_level": "high",
    "maintainers": [
      "tarunag10"
    ],
    "githubUrl": "https://github.com/tarunag10/foi-tracker",
    "toolKey": "foi",
    "iconClass": "amber",
    "icon": "◐",
    "summary": "Track FOI requests, deadlines, and escalations across public authorities."
  },
  {
    "id": "case-builder",
    "name": "Case Builder",
    "repo": "tarunag10/case-builder",
    "demo": "https://case-builder.vercel.app/",
    "category": "case-management",
    "status": "usable",
    "risk_level": "medium",
    "maintainers": [
      "tarunag10"
    ],
    "githubUrl": "https://github.com/tarunag10/case-builder",
    "toolKey": "case",
    "iconClass": "rose",
    "icon": "◧",
    "summary": "Combine letters, evidence, deadlines, and journeys into one portable case file."
  }
];

return { publicRepositories };
})();

// ===== src/workflows.js =====
const __m6__Users_tarunagarwal_Documents_1_App_Developement_Tarun_Open_Access_UK_open_access_uk_site_src_workflows_js = (() => {
const workflows = {
  information: {
    title: 'Get information',
    body: 'Start with a letter or template, keep the request focused, export a copy, use the FOI tracker to manage deadlines across authorities, and use the directory to understand where to go next.',
    steps: [
      'Choose a request type.',
      'Draft locally in the browser.',
      'Track FOI deadlines in the FOI tracker.',
      'Export a copy and keep notes.'
    ]
  },
  forms: {
    title: 'Fix an inaccessible form',
    body: 'Use the accessible forms library to inspect a service journey, identify missing labels or grouped-control issues, and export a shareable JSON spec.',
    steps: [
      'Pick a public-service form pattern.',
      'Review readiness and notes.',
      'Copy or download the improved spec.'
    ]
  },
  escalate: {
    title: 'Escalate a case',
    body: 'Map the right escalation route, gather evidence, save a local plan in the Case Builder, and keep official links close to the next action.',
    steps: [
      'Search the issue.',
      'Build an action plan in the Case Builder.',
      'Add evidence and journey steps.',
      'Export a handoff pack for an adviser.'
    ]
  },
  contribute: {
    title: 'Build or contribute',
    body: 'Start from the parent GitHub repo, choose a public tool, and use contributor docs to make a focused improvement.',
    steps: [
      'Open the parent repo.',
      'Pick a focused issue or improvement.',
      'Run the relevant checks before opening a pull request.'
    ]
  }
};

return { workflows };
})();

// ===== ../shared/privacy/local-storage.mjs =====
const __m7__Users_tarunagarwal_Documents_1_App_Developement_Tarun_Open_Access_UK_shared_privacy_local_storage_mjs = (() => {
const storageRegistry = [
  {
    key: 'open-access-uk:letter-generator:draft',
    tool: 'letter-generator',
    label: 'Letter draft',
    storage: 'localStorage',
    contains: 'Draft letter fields entered by the user'
  },
  {
    key: 'open-access-uk:accessible-forms:review-notes',
    tool: 'accessible-forms',
    label: 'Form review notes',
    storage: 'localStorage',
    contains: 'Local reviewer notes for form examples'
  },
  {
    key: 'open-access-uk:saved-action-plans',
    tool: 'public-service-directory',
    label: 'Saved escalation plans',
    storage: 'localStorage',
    contains: 'Saved route names, evidence checklists, and escalation notes'
  },
  {
    key: 'open-access-uk:legal-templates:favourites',
    tool: 'legal-templates',
    label: 'Favourite templates',
    storage: 'localStorage',
    contains: 'Template ids marked as favourites'
  },
  {
    key: 'open-access-uk:design-system:shortlist',
    tool: 'design-system',
    label: 'Component shortlist',
    storage: 'localStorage',
    contains: 'Design-system component names saved locally'
  },
  {
    key: 'open-access-uk:saved-file-list-examples',
    tool: 'maintainer-helper',
    label: 'Saved maintainer examples',
    storage: 'localStorage',
    contains: 'Repository file-list examples saved by maintainers'
  },
  {
    key: 'open-access-uk:theme',
    tool: 'suite',
    label: 'Theme preference',
    storage: 'localStorage',
    contains: 'Chosen light or dark theme for the suite'
  },
  {
    key: 'open-access-uk:evidence-handoff',
    tool: 'suite',
    label: 'Evidence handoff',
    storage: 'localStorage',
    contains: 'Evidence checklist passed between the letter generator and directory'
  },
  {
    key: 'open-access-uk:legal-templates:collections',
    tool: 'legal-templates',
    label: 'Template collections',
    storage: 'localStorage',
    contains: 'Named local groupings of favourite templates'
  },
  {
    key: 'open-access-uk:foi-tracker:requests',
    tool: 'foi-tracker',
    label: 'FOI request tracker',
    storage: 'localStorage',
    contains: 'Tracked FOI requests, deadlines, response notes, and escalation notes'
  },
  {
    key: 'open-access-uk:foi-tracker:form-draft',
    tool: 'foi-tracker',
    label: 'FOI tracker form draft',
    storage: 'localStorage',
    contains: 'In-progress FOI tracker form fields'
  },
  {
    key: 'open-access-uk:case-builder:cases',
    tool: 'case-builder',
    label: 'Case builder',
    storage: 'localStorage',
    contains: 'Saved cases with evidence, letters, and journey steps'
  },
  {
    key: 'open-access-uk:case-builder:form-draft',
    tool: 'case-builder',
    label: 'Case builder form draft',
    storage: 'localStorage',
    contains: 'In-progress case builder form fields'
  },
  {
    key: 'open-access-uk:case-builder:active',
    tool: 'case-builder',
    label: 'Active case id',
    storage: 'localStorage',
    contains: 'Identifier of the most recently selected case'
  }
];

function clearKnownStorage(storage, registry = storageRegistry) {
  if (!storage) return { cleared: [], failed: registry.map((item) => item.key) };

  const cleared = [];
  const failed = [];
  for (const item of registry) {
    try {
      storage.removeItem(item.key);
      cleared.push(item.key);
    } catch {
      failed.push(item.key);
    }
  }
  return { cleared, failed };
}

function describeStorageRegistry(registry = storageRegistry) {
  return registry.map((item) => `${item.label} (${item.tool}): ${item.contains}`);
}

return { storageRegistry, clearKnownStorage, describeStorageRegistry };
})();

// ===== src/privacy-centre.js =====
const __m8__Users_tarunagarwal_Documents_1_App_Developement_Tarun_Open_Access_UK_open_access_uk_site_src_privacy_centre_js = (() => {
const { storageRegistry: storageRegistry, clearKnownStorage: clearKnownStorage } = __m7__Users_tarunagarwal_Documents_1_App_Developement_Tarun_Open_Access_UK_shared_privacy_local_storage_mjs;

function readPresence(key) {
  try {
    const value = window.localStorage.getItem(key);
    return value === null ? null : value.length;
  } catch {
    return null;
  }
}

function initPrivacyCentre(mountSelector = '#privacy-centre') {
  const mount = document.querySelector(mountSelector);
  if (!mount) return;

  function render() {
    const list = document.createElement('ul');
    list.className = 'privacy-list';
    list.setAttribute('aria-label', 'Local data stored in this browser');
    for (const item of storageRegistry) {
      const size = readPresence(item.key);
      const li = document.createElement('li');
      li.className = 'privacy-item';
      const title = document.createElement('strong');
      title.textContent = `${item.label} (${item.tool})`;
      const detail = document.createElement('p');
      detail.textContent =
        size === null
          ? `${item.contains} — nothing stored.`
          : `${item.contains} — ${size} characters stored.`;
      li.append(title, detail);
      list.append(li);
    }
    const clearAll = document.createElement('button');
    clearAll.type = 'button';
    clearAll.className = 'secondary';
    clearAll.textContent = 'Clear all local data';
    clearAll.addEventListener('click', () => {
      clearKnownStorage(window.localStorage);
      render();
      status.textContent = 'Cleared all known local data from this browser.';
    });
    const status = document.createElement('p');
    status.setAttribute('role', 'status');
    status.setAttribute('aria-live', 'polite');
    mount.replaceChildren(list, clearAll, status);
  }

  render();
}

return { initPrivacyCentre };
})();

// ===== ../shared/search/index.mjs =====
const __m9__Users_tarunagarwal_Documents_1_App_Developement_Tarun_Open_Access_UK_shared_search_index_mjs = (() => {
// Static client-side suite index + ranked substring search. No network.

const suiteIndex = [
  {
    id: 'letter-generator',
    kind: 'tool',
    title: 'Public-Service Letter Generator',
    url: 'https://letter-generator-psi.vercel.app',
    keywords: [
      'letter',
      'foi',
      'freedom of information',
      'subject access',
      'sar',
      'adjustment',
      'complaint',
      'deadline'
    ]
  },
  {
    id: 'accessible-forms',
    kind: 'tool',
    title: 'Accessible Public Forms',
    url: 'https://accessible-forms-two.vercel.app',
    keywords: ['forms', 'accessibility', 'wcag', 'labels', 'readiness', 'remediation']
  },
  {
    id: 'public-service-directory',
    kind: 'tool',
    title: 'Public Service Directory',
    url: 'https://public-service-directory.vercel.app',
    keywords: ['escalation', 'ombudsman', 'complaint', 'council', 'regulator', 'readiness', 'route']
  },
  {
    id: 'legal-templates',
    kind: 'tool',
    title: 'Legal Templates UK',
    url: 'https://legal-templates-seven.vercel.app',
    keywords: ['template', 'refund', 'chargeback', 'housing', 'rail', 'data', 'sar', 'letter']
  },
  {
    id: 'design-system',
    kind: 'tool',
    title: 'Open Access Design System',
    url: 'https://design-system-two-delta.vercel.app',
    keywords: ['tokens', 'components', 'contrast', 'design', 'accessibility', 'recipes']
  },
  {
    id: 'workflow-information',
    kind: 'workflow',
    title: 'Workflow: Request information',
    url: 'https://openaccessuk.vercel.app/#workflows',
    keywords: ['foi', 'information', 'request', 'workflow']
  },
  {
    id: 'workflow-escalate',
    kind: 'workflow',
    title: 'Workflow: Escalate a complaint',
    url: 'https://openaccessuk.vercel.app/#workflows',
    keywords: ['escalate', 'complaint', 'ombudsman', 'workflow']
  }
];

function searchSuite(query, index = suiteIndex) {
  const q = String(query || '')
    .trim()
    .toLowerCase();
  if (!q) return [];
  const scored = [];
  for (const entry of index) {
    const title = entry.title.toLowerCase();
    const keywords = entry.keywords.join(' ').toLowerCase();
    let score = 0;
    if (title === q) score += 100;
    if (title.startsWith(q)) score += 40;
    if (title.includes(q)) score += 20;
    if (entry.keywords.some((k) => k.toLowerCase() === q)) score += 30;
    if (keywords.includes(q)) score += 10;
    if (score > 0) scored.push({ ...entry, score });
  }
  return scored.sort((a, b) => b.score - a.score);
}

return { suiteIndex, searchSuite };
})();

// ===== src/command-palette.js =====
const __m10__Users_tarunagarwal_Documents_1_App_Developement_Tarun_Open_Access_UK_open_access_uk_site_src_command_palette_js = (() => {
const { searchSuite: searchSuite, suiteIndex: suiteIndex } = __m9__Users_tarunagarwal_Documents_1_App_Developement_Tarun_Open_Access_UK_shared_search_index_mjs;

function initCommandPalette({ root = document } = {}) {
  const dialog = root.querySelector('#command-palette');
  const input = root.querySelector('#command-input');
  const list = root.querySelector('#command-results');
  const openButton = root.querySelector('#command-open');
  if (!dialog || !input || !list) return;

  let active = -1;
  let current = [];

  function render(query) {
    current = query ? searchSuite(query) : suiteIndex.map((e) => ({ ...e }));
    active = current.length ? 0 : -1;
    list.replaceChildren(
      ...current.map((entry, index) => {
        const li = document.createElement('li');
        const link = document.createElement('a');
        link.href = entry.url;
        link.textContent = entry.title;
        link.setAttribute('role', 'option');
        link.id = `command-option-${index}`;
        link.setAttribute('aria-selected', String(index === active));
        li.append(link);
        return li;
      })
    );
    input.setAttribute('aria-activedescendant', active >= 0 ? `command-option-${active}` : '');
  }

  function open() {
    dialog.hidden = false;
    input.value = '';
    render('');
    input.focus();
  }
  function close() {
    dialog.hidden = true;
    openButton?.focus();
  }

  openButton?.addEventListener('click', open);
  document.addEventListener('keydown', (event) => {
    if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 'k') {
      event.preventDefault();
      dialog.hidden ? open() : close();
    } else if (!dialog.hidden && event.key === 'Escape') {
      close();
    }
  });
  input.addEventListener('input', () => render(input.value));
  input.addEventListener('keydown', (event) => {
    if (event.key === 'ArrowDown') {
      event.preventDefault();
      active = Math.min(active + 1, current.length - 1);
      render(input.value);
    } else if (event.key === 'ArrowUp') {
      event.preventDefault();
      active = Math.max(active - 1, 0);
      render(input.value);
    } else if (event.key === 'Enter' && active >= 0) {
      event.preventDefault();
      window.location.href = current[active].url;
    }
  });
}

return { initCommandPalette };
})();

// ===== src/continue.js =====
const __m11__Users_tarunagarwal_Documents_1_App_Developement_Tarun_Open_Access_UK_open_access_uk_site_src_continue_js = (() => {
const { storageRegistry: storageRegistry } = __m7__Users_tarunagarwal_Documents_1_App_Developement_Tarun_Open_Access_UK_shared_privacy_local_storage_mjs;

const TOOL_URLS = {
  'letter-generator': 'https://letter-generator-psi.vercel.app',
  'accessible-forms': 'https://accessible-forms-two.vercel.app',
  'public-service-directory': 'https://public-service-directory.vercel.app',
  'legal-templates': 'https://legal-templates-seven.vercel.app',
  'design-system': 'https://design-system-two-delta.vercel.app'
};

function initContinue(mountSelector = '#continue') {
  const mount = document.querySelector(mountSelector);
  if (!mount) return;

  const resumable = storageRegistry.filter((item) => {
    if (!TOOL_URLS[item.tool]) return false;
    try {
      return window.localStorage.getItem(item.key) !== null;
    } catch {
      return false;
    }
  });

  if (!resumable.length) {
    mount.hidden = true;
    return;
  }
  mount.hidden = false;
  const cards = resumable.map((item) => {
    const card = document.createElement('article');
    card.className = 'card';
    const h3 = document.createElement('h3');
    h3.textContent = item.label;
    const p = document.createElement('p');
    p.textContent = item.contains;
    const a = document.createElement('a');
    a.href = TOOL_URLS[item.tool];
    a.textContent = 'Continue →';
    card.append(h3, p, a);
    return card;
  });
  const wrap = document.createElement('div');
  wrap.className = 'cards';
  wrap.append(...cards);
  mount.replaceChildren(wrap);
}

return { initContinue };
})();

// ===== src/app.js =====
const { initTheme: initTheme } = __m2__Users_tarunagarwal_Documents_1_App_Developement_Tarun_Open_Access_UK_open_access_uk_site_src_theme_js;
const { track: track } = __m3__Users_tarunagarwal_Documents_1_App_Developement_Tarun_Open_Access_UK_open_access_uk_site_src_analytics_js;
const { textElement: textElement, setPressed: setPressed, setStatus: setStatus } = __m4__Users_tarunagarwal_Documents_1_App_Developement_Tarun_Open_Access_UK_open_access_uk_site_src_dom_js;
const { publicRepositories: publicRepositories } = __m5__Users_tarunagarwal_Documents_1_App_Developement_Tarun_Open_Access_UK_open_access_uk_site_src_repositories_js;
const { workflows: workflows } = __m6__Users_tarunagarwal_Documents_1_App_Developement_Tarun_Open_Access_UK_open_access_uk_site_src_workflows_js;
const { initPrivacyCentre: initPrivacyCentre } = __m8__Users_tarunagarwal_Documents_1_App_Developement_Tarun_Open_Access_UK_open_access_uk_site_src_privacy_centre_js;
const { initCommandPalette: initCommandPalette } = __m10__Users_tarunagarwal_Documents_1_App_Developement_Tarun_Open_Access_UK_open_access_uk_site_src_command_palette_js;
const { initContinue: initContinue } = __m11__Users_tarunagarwal_Documents_1_App_Developement_Tarun_Open_Access_UK_open_access_uk_site_src_continue_js;

const workflowDetail = document.querySelector('#workflow-detail');
const workflowCards = [...document.querySelectorAll('[data-workflow]')];
const productPanels = [...document.querySelectorAll('[data-product-panel]')];
const copyTokens = document.querySelector('#copyTokens');
const copyStatus = document.querySelector('#copy-status');
const navToggle = document.querySelector('.nav-toggle');
const primaryNav = document.querySelector('#primary-nav');

function renderToolCards() {
  const grid = document.querySelector('[data-tool-grid]');
  if (!grid || !publicRepositories.length) return;

  const cards = publicRepositories.map((repo, index) => {
    const article = document.createElement('article');
    article.className = `tool-card${index === 0 ? ' is-active' : ''}`;
    article.dataset.tool = repo.toolKey;

    const icon = textElement('span', repo.icon);
    icon.className = `tool-icon ${repo.iconClass}`;

    const heading = textElement('h3', repo.name);
    const summary = textElement('p', repo.summary);
    const risk = textElement('p', `${repo.risk_level} risk · ${repo.status}`);
    risk.className = 'tool-meta';

    const links = document.createElement('div');
    links.className = 'tool-links';
    const demo = document.createElement('a');
    demo.href = repo.demo;
    demo.textContent = 'Launch tool';
    const github = document.createElement('a');
    github.href = repo.githubUrl;
    github.textContent = 'GitHub';
    links.append(demo, github);

    article.append(icon, heading, summary, risk, links);
    return article;
  });

  grid.replaceChildren(...cards);
}

function renderWorkflow(key) {
  const workflow = workflows[key] || workflows.information;
  if (!workflowDetail) return;

  const heading = textElement('h3', workflow.title);
  const body = textElement('p', workflow.body);
  const list = document.createElement('ol');
  workflow.steps.forEach((step) => list.append(textElement('li', step)));

  workflowDetail.replaceChildren(heading, body, list);
  setPressed(workflowCards, key);
  track('workflow_selected', { key });
}

function activateTool(key) {
  [...document.querySelectorAll('[data-tool]')].forEach((card) =>
    card.classList.toggle('is-active', card.dataset.tool === key)
  );
  productPanels.forEach((panel) => {
    panel.style.borderColor = panel.dataset.productPanel === key ? 'var(--red)' : '';
    panel.style.transform = panel.dataset.productPanel === key ? 'translateY(-4px)' : '';
  });
}

function selectAdjacentWorkflow(current, direction) {
  const index = workflowCards.indexOf(current);
  const next = workflowCards[(index + direction + workflowCards.length) % workflowCards.length];
  next?.focus();
  if (next?.dataset.workflow) renderWorkflow(next.dataset.workflow);
}

workflowCards.forEach((card) => {
  card.addEventListener('click', () => renderWorkflow(card.dataset.workflow));
  card.addEventListener('keydown', (event) => {
    if (event.key === 'ArrowRight' || event.key === 'ArrowDown') {
      event.preventDefault();
      selectAdjacentWorkflow(card, 1);
    }
    if (event.key === 'ArrowLeft' || event.key === 'ArrowUp') {
      event.preventDefault();
      selectAdjacentWorkflow(card, -1);
    }
  });
});

function bindToolCards() {
  [...document.querySelectorAll('[data-tool]')].forEach((card) => {
    card.addEventListener('mouseenter', () => activateTool(card.dataset.tool));
    card.addEventListener('focusin', () => activateTool(card.dataset.tool));
  });
}

navToggle?.addEventListener('click', () => {
  const open = navToggle.getAttribute('aria-expanded') !== 'true';
  navToggle.setAttribute('aria-expanded', String(open));
  primaryNav?.classList.toggle('is-open', open);
});

primaryNav?.addEventListener('click', (event) => {
  if (!event.target.closest('a')) return;
  navToggle?.setAttribute('aria-expanded', 'false');
  primaryNav.classList.remove('is-open');
});

copyTokens?.addEventListener('click', async () => {
  const tokenText = document.querySelector('.code-window code')?.textContent.trim() || '';
  try {
    await navigator.clipboard.writeText(tokenText);
    copyTokens.textContent = 'Copied';
    setStatus(copyStatus, 'Design tokens copied.');
  } catch {
    copyTokens.textContent = 'Select and copy';
    setStatus(copyStatus, 'Copy failed. Select and copy the tokens manually.');
  }
  window.setTimeout(() => {
    copyTokens.textContent = 'Copy tokens';
  }, 1800);
});

renderToolCards();
bindToolCards();
renderWorkflow('information');

initTheme('#theme-toggle');
initPrivacyCentre('#privacy-centre');
initCommandPalette({ root: document });
initContinue('#continue');
