// Generated by scripts/sync-static-metadata.mjs. Do not edit by hand.
export const publicRepositories = [
  {
    "id": "letter-generator",
    "name": "Reasonable Adjustment Letter Generator",
    "repo": "tarunag10/letter-generator",
    "demo": "https://letter-generator-psi.vercel.app/",
    "category": "letters",
    "status": "usable",
    "risk_level": "high",
    "maintainers": [
      "tarunag10"
    ],
    "githubUrl": "https://github.com/tarunag10/letter-generator",
    "toolKey": "letters",
    "iconClass": "blue",
    "icon": "▣",
    "summary": "Create useful letters, plan response windows, and follow up with confidence."
  },
  {
    "id": "accessible-forms",
    "name": "Accessible Public Forms",
    "repo": "tarunag10/accessible-forms",
    "demo": "https://accessible-forms-two.vercel.app/",
    "category": "forms",
    "status": "usable",
    "risk_level": "medium",
    "maintainers": [
      "tarunag10"
    ],
    "githubUrl": "https://github.com/tarunag10/accessible-forms",
    "toolKey": "forms",
    "iconClass": "green",
    "icon": "▤",
    "summary": "Check readiness, export JSON specs, and generate remediation reports."
  },
  {
    "id": "public-service-directory",
    "name": "Public Service Directory",
    "repo": "tarunag10/public-service-directory",
    "demo": "https://public-service-directory.vercel.app/",
    "category": "directory",
    "status": "usable",
    "risk_level": "high",
    "maintainers": [
      "tarunag10"
    ],
    "githubUrl": "https://github.com/tarunag10/public-service-directory",
    "toolKey": "directory",
    "iconClass": "lime",
    "icon": "⌂",
    "summary": "Find the right route and generate escalation readiness reports."
  },
  {
    "id": "legal-templates",
    "name": "Legal Templates UK",
    "repo": "tarunag10/legal-templates",
    "demo": "https://legal-templates-seven.vercel.app/",
    "category": "templates",
    "status": "usable",
    "risk_level": "high",
    "maintainers": [
      "tarunag10"
    ],
    "githubUrl": "https://github.com/tarunag10/legal-templates",
    "toolKey": "templates",
    "iconClass": "violet",
    "icon": "◫",
    "summary": "Bundle plain-English templates into reusable text and Markdown packs."
  },
  {
    "id": "design-system",
    "name": "Open Access Design System",
    "repo": "tarunag10/design-system",
    "demo": "https://design-system-two-delta.vercel.app/",
    "category": "design-system",
    "status": "usable",
    "risk_level": "low",
    "maintainers": [
      "tarunag10"
    ],
    "githubUrl": "https://github.com/tarunag10/design-system",
    "toolKey": "design",
    "iconClass": "cyan",
    "icon": "⌘",
    "summary": "Use accessible components, tokens, and implementation recipes."
  }
];
